services:
  - type: web
    name: quotex-bot
    runtime: python
    buildCommand: |
      rm -rf /var/lib/apt/lists/* && \
      apt-get update -qq && \
      apt-get install -y --no-install-recommends chromium chromium-driver && \
      pip install --no-cache-dir -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: CHROME_EXECUTABLE_PATH
        value: /usr/bin/chromium-browser
      - key: CHROMEDRIVER_EXECUTABLE_PATH
        value: /usr/bin/chromedriver
